// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmgtyhbvtlpggzgicqvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ3R5aGJ2dGxwZ2d6Z2ljcXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NDg5NjEsImV4cCI6MjA3ODMyNDk2MX0.rafovxo4a5F18yg58Gb4phLyA0QJ220ohkxCRgQQoe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});